name: Release Spring Boot & Docker

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Complete Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name:  Detect version bump
        id: bump
        run: |
          BRANCH="${ {github.event.pull_request.head.ref }}"
          echo "Rama origen: $BRANCH"

          if [[ "$BRANCH" == feature/* ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == fix/* ]]; then
            echo "type=patch" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == major/* || "$BRANCH" == breaking/* ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
          fi

          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven


      - name: Bump version in pom.xml
        run: |
          mvn build-helper:parse-version versions:set \
            -DnewVersion=$(
              if [ "${{ steps.bump.outputs.type }}" = "major" ]; then
                echo "\${ parsedVersion.nextMajorVersion }.0.0"
              elif [ "${{ steps.bump.outputs.type }}" = "minor" ]; then
                echo "\${ parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion }.0"
              else
                echo "\${ parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion }"
              fi
            ) \
            versions:commit


      - name: Commit and tag version
        run: |
          VERSION=${ mvn help:evaluate -Dexpression=project.version -q -DforceStdout }
          echo "Nueva version: $VERSION"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "chore(release): v$VERSION
          git tag v$VERSION


      - name: Push to main + tags
        run: |
           git push origin main --tags

  
      - name:  Build JAR
        run: mvn clean package -DskipTests


      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USER }}" --password-stdin


      - name:  Build Docker image
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

          docker build \
            -t ${{ secrets.DOCKER_USER }}/control-finanzas-back:$VERSION \
            -t ${{ secrets.DOCKER_USER }}/control-finanzas-back:latest \


      - name: Push image Docker
        run: |
          VERSION=$(mvn help: evaluate -Dexpression=project.version -q -DforceStdout)
          docker push ${{ secrets.DOCKER_USERR }}/control-finanzas-back:$VERSION
          docker push ${{ secrets.DOCKER_USER }}/control-finanzas-back:latest
    
